matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - bc
            - samtools
            - parallel
            - meson
            - ninja-build
script:
  - apt-cache pkgnames|grep hts|grep lib
  - mkdir build
  - meson build/
  - ninja -C build/
  - meson test --timeout-multiplier 8 -C build/
