# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-9 g++-9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - gcc --version && g++ --version
  - sudo apt-get install -qq bc samtools parallel
script:
  - make -j4 && make -j4 test
